name: Sync Main
on:
  workflow_dispatch:
  schedule:
    - cron:  '55 * * * *'
jobs:
  sync-main:
    name: Sync-main
    runs-on: ubuntu-latest
    if: github.repository == 'cvedb/poc-git'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Git config
        shell: bash
        run: |
          git config user.name "cvedb"
          git config user.email "118260833+gitworkflows@users.noreply.github.com"
      - name: Sync Main
        shell: bash
        run: |
          set -x
          git fetch
          git remote add upstream https://github.com/trickest/cve.git
          git fetch upstream --tags --force
